
platform :ios, '10.0'

inhibit_all_warnings!

use_frameworks!

target '${POD_NAME}' do

  pod 'SwiftyUserDefaults'
  pod 'Reusable'
  pod 'SnapKit'
  pod 'Then'
  pod 'SwifterSwift'
  pod 'Alamofire'

end



 
