
platform :ios, '10.0'

inhibit_all_warnings!

use_frameworks!

target '${POD_NAME}_Example' do

  pod 'SwiftyUserDefaults'
  pod 'Reusable'
  pod 'SnapKit'
  pod 'Then'
  pod 'SwifterSwift'
  pod 'Alamofire'
  
  pod '${POD_NAME}', :path => '../'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end



 
