# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'

inhibit_all_warnings!

use_frameworks!

target '${POD_NAME}' do
  pod 'AFNetworking'
  pod 'YYKit'
  pod 'SDWebImage' 
  pod 'Masonry' 
  pod 'SVProgressHUD'

end 